### ISSUE TITLE
stuck with curl under alacritty

### ISSUE THREAD

**Issue by iysheng** [klesh/dict.sh#1]
Hello, this tool is pretty cool, but when I use this tool under terminal. it stucks as blew:
```
▸ d hello world
curl: (3) URL using bad/illegal format or missing URL
```
why would this happen ? :joy:

**Comment by klesh** [comment]
Interesting, can you type `curl -V` and paste the output here?
Also, please try following command and paste the output as well:
```sh
curl -SsLG "http://dict.youdao.com/w/eng/hello world/"
```

**Comment by iysheng** [comment]
> Interesting, can you type `curl -V` and paste the output here? Also, please try following command and paste the output as well:
> 
> ```shell
> curl -SsLG "http://dict.youdao.com/w/eng/hello world/"
> ```

sure. the outputs just below.
``` shell
▸ curl -V
curl 7.82.0 (x86_64-solus-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.11 libssh2/1.9.0_DEV nghttp2/1.41.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
▸ curl -SsLG "http://dict.youdao.com/w/eng/hello world/"
curl: (3) URL using bad/illegal format or missing URL
```

**Comment by klesh** [comment]
Interesting... seems like newer version doesn't encode URL

**Comment by klesh** [comment]
Filed a bug on https://github.com/curl/curl/issues/8654

**Comment by iysheng** [comment]
> Filed a bug on https://github.com/curl/curl/issues/8654 

OK，let us wait for reply。😊

**Comment by klesh** [comment]
@iysheng Fixed, please re-pull and re-install to upgrade

**Comment by iysheng** [comment]
> @iysheng Fixed, please re-pull and re-install to upgrade

Great, it's ok now,thanks a lot.
